// DO NOT MODIFY. This file is automatically generated by Firebase Studio.
import { initializeApp, getApp, getApps } from 'firebase/app';

const firebaseConfig = {"projectId":"honeyhub-i86x2","appId":"1:671556324157:web:de233caf0c7a4d9acc1354","storageBucket":"honeyhub-i86x2.firebasestorage.app","apiKey":"AIzaSyDU-uHHhXGKT7t5vbru9vOKFnN8PQNsWR4","authDomain":"honeyhub-i86x2.firebaseapp.com","measurementId":"","messagingSenderId":"671556324157"};

function getFirebaseApp() {
  if (getApps().length === 0) {
    return initializeApp(firebaseConfig);
  } else {
    return getApp();
  }
}

export const firebaseApp = getFirebaseApp();
